# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_auto_20181017_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
        migrations.AddField(
            model_name='review',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='belt.Book'),
            preserve_default=False,
        ),
    ]
