# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0006_auto_20181017_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='creator',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt.Book'),
        ),
    ]
